FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
EXPOSE 5001:5001
WORKDIR /src


COPY ProductManagement.Gateway/ProductManagement.Gateway.csproj ./
RUN dotnet restore


COPY ProductManagement.Gateway/ .
RUN dotnet publish -c Release -o /app/out



FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /src


WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "ProductManagement.Gateway.dll"]
