version: "3.9"
services:
  couchbase1:
    tty: true
    stdin_open: true
    container_name: couchbase1
    image: couchbase/server
    restart: always
    volumes:
      - couchbase1-data:/var/lib/couchbase1/data
    networks:
      product-management-network:
        ipv4_address: 172.16.101.11
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    ulimits:
      nproc: 65535
      core:
        soft: 100000000
        hard: 100000000
      memlock:
        soft: 100000000
        hard: 100000000
      nofile:
        soft: 40960
        hard: 40960
  couchbase2:
    tty: true
    stdin_open: true
    restart: always
    container_name: couchbase2
    image: couchbase/server
    volumes:
      - couchbase2-data:/var/lib/couchbase2/data
    networks:
      product-management-network:
        ipv4_address: 172.16.101.12
    links:
      - couchbase1
    depends_on:
      - couchbase1
    ports:
      - 18091:8091
      - 18092:8092
      - 18093:8093
      - 18094:8094
      - 21210:11210
  
  consul:
    image: consul
    restart: always
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    expose:
      - "8500"
    command: agent -server -bootstrap -ui -client=0.0.0.0
    networks:
      product-management-network:
        ipv4_address: 172.16.101.14
  gateway:
    restart: always
    depends_on:
      - consul
    image: api-gateway
    build:
      context: .
      dockerfile: Dockerfile-Gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      product-management-network:
        ipv4_address: 172.16.101.15
    ports:
      - "5001:5001"
    expose:
      - "5001"
    links:
      - consul
  product-api-1:
    restart: always
    depends_on:
      - consul
      - couchbase1
      - couchbase2
      - es01
      - es02
    image: product-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SERVICE_URL=http://product-api-1:5011
    networks:
      product-management-network:
        ipv4_address: 172.16.101.20
    ports:
      - "5011:5011"
    expose:
      - "5011"
    deploy:
      resources:
        limits:
          memory: 150M
        reservations:
          memory: 75M
  product-api-2:
    restart: always
    depends_on:
      - consul
      - couchbase1
      - couchbase2
      - es01
      - es02
    image: product-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SERVICE_URL=http://product-api-2:5012
    networks:
      product-management-network:
        ipv4_address: 172.16.101.21
    ports:
      - "5012:5012"
    expose:
      - "5012"
    deploy:
      resources:
        limits:
          memory: 150M
        reservations:
          memory: 75M

  
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - product-management-network
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    ports:
      - 9201:9201
    networks:
      - product-management-network

  kib01:
    depends_on:
      - es01
      - es02
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - product-management-network
networks:
  product-management-network:
    name: product-management-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.101.0/24
volumes:
  couchbase1-data:
  couchbase2-data:
  data01:
    driver: local
  data02:
    driver: local